### ISSUE TITLE
Doing bonus.md Routing causes error

### ISSUE THREAD

**Issue by letsbelopez** [Shopify/unite-react-node-app-workshop#16]
Getting error `Uncaught Error: You should not use <Route> or withRouter() outside a <Router>`

I made the error disappear by wrapping <BrowserRouter> component around <App /> in "client/index.js"

```
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';

import App from '../app/App';

console.log('hello from the client');

ReactDOM.hydrate(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById('app'),
);
```

**Comment by junaid33** [comment]
Yes this is the solution. Server side, you are wrapping the routes with Static Router so you need Browser router client side.
